#!/usr/bin/env bash

sudo pacman -Syyuu
sudo pacman -S --needed git base-devel go

cd ~
rm -rf ~/dotfiles
git clone https://github.com/TiagoLisboa/dotfiles.git ~/dotfiles
cd ~/dotfiles

# install yay
rm -rf ~/yay
git clone https://aur.archlinux.org/yay.git ~/yay
cd ~/yay
makepkg -si
cd -

yay -Syu
yay -S neovim nvim-packer-git curl tmux fish

# asdf configuration
rm -rf ~/.asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2
mkdir -p ~/.config/fish/completions
rm ~/.config/fish/completions/asdf.fish
ln -s ~/.asdf/completions/asdf.fish ~/.config/fish/completions
. $HOME/.asdf/asdf.sh

# setup nodejs with asdf
~/.asdf/bin/asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
~/.asdf/bin/asdf install nodejs latest
~/.asdf/bin/asdf global nodejs latest

# install tpm
rm -rf ~/.tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# install fisher
/usr/bin/fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"

rm -rf ~/.config/nvim
ln -s $(pwd)/nvim ~/.config/nvim

rm -rf ~/.tmux.conf
ln -s $(pwd)/.tmux.conf ~/.tmux.conf

rm -rf ~/.config/fish
ln -s $(pwd)/fish ~/.config/fish

nvim --headless +PlugInstall +q
